version: '3.8'

services:
  azure-sql-edge:
    image: mcr.microsoft.com/azure-sql-edge:latest
    platform: linux/amd64
    container_name: azure-sql-edge
    cap_add:
      - SYS_PTRACE
    environment:
      - ACCEPT_EULA=${ACCEPT_EULA}
      - MSSQL_SA_PASSWORD=${MSSQL_SA_PASSWORD}
      - MSSQL_PID=${MSSQL_PID}
    ports:
      - "${SQL_PORT}:1433"
    volumes:
      - sql_data:/var/opt/mssql
      - ~/docker-volumes/sql-data:/data
    restart: unless-stopped
    networks:
      - sql-network

volumes:
  sql_data:

networks:
  sql-network:
    driver: bridge
